### ISSUE TITLE
Uh2Tk1 - Configurar el entorno de desarrollo para ESP32

### ISSUE THREAD

**Issue by FerCbr** [ISPC-TST-PI-I-2024/capa-de-procesamiento-grupo-plata#23]
### Uh2Tk1 - Configurar el entorno de desarrollo para ESP32
**Descripción**: Configurar el entorno de desarrollo para ESP32 utilizando VSCode y PlatformIO.
#### Pasos:
1. Instalar VSCode y el complemento PlatformIO.
2. Configurar el proyecto en PlatformIO para ESP32.
3. Realizar una prueba de conexión básica del ESP32.

**Comment by NicolasBa27** [comment]
![build](https://github.com/user-attachments/assets/204ea154-8ff0-4208-8002-02227eaa17cb)
![Terminal](https://github.com/user-attachments/assets/229b11e9-8315-4c41-a929-788f9448aab2)
![Upload](https://github.com/user-attachments/assets/db8a610b-1b1d-405f-852d-cab97fb7a7fd)

Uh2Tk1 - Configurar el entorno de desarrollo para ESP32
Descripción: Configurar el entorno de desarrollo para ESP32 utilizando VSCode y PlatformIO.

Pasos:
Instalar VSCode y el complemento PlatformIO.
Configurar el proyecto en PlatformIO para ESP32.
Realizar una prueba de conexión básica del ESP32.
