### ISSUE TITLE
Uh1Tk4 - Configurar el entorno de desarrollo en Python

### ISSUE THREAD

**Issue by FerCbr** [ISPC-TST-PI-I-2024/capa-de-procesamiento-grupo-plata#3]
### Uh1Tk4 - Configurar el entorno de desarrollo en Python
**Descripción**: Preparar el entorno de desarrollo en Python para interactuar correctamente con la API RESTful, asegurando que todas las dependencias están configuradas.
#### Pasos:
1. Instalar Python y crear un entorno virtual para el proyecto.
2. Instalar las librerías necesarias, como `requests` y `json`.
3. Probar la conexión básica con la API para verificar que todo funciona correctamente.

**Comment by NicolasBa27** [comment]
![image](https://github.com/user-attachments/assets/fec63825-87f2-40df-8d92-ecd7556347ed)

Test
