### ISSUE TITLE
Uh3Tk1 - Definir las funcionalidades del middleware

### ISSUE THREAD

**Issue by FerCbr** [ISPC-TST-PI-I-2024/capa-de-procesamiento-grupo-plata#33]
### Uh3Tk1 - Definir las funcionalidades del middleware
**Descripción**: Definir las funcionalidades necesarias para que el middleware gestione la comunicación entre los dispositivos Edge y la API.
#### Pasos:
1. Revisar las necesidades de comunicación entre los dispositivos Edge y la API.
2. Esquematizar el flujo de datos entre los dispositivos Edge y la API RESTful.
3. Definir los puntos clave de transformación de datos en el middleware.

**Comment by diegote7** [comment]
Funcionalidades del Middleware para el Proyecto AQI
Este documento detalla las funcionalidades esenciales que debe tener el middleware encargado de gestionar la comunicación entre los dispositivos Edge (como el ESP32) y una API RESTful que almacena los datos de sensores en una base de datos remota. Este middleware está diseñado para procesar varios datos de sensores en una única solicitud y desglosarlos para ser almacenados en la base de datos, todo mientras maneja la autenticación de usuarios y dispositivos.
Necesidades del Sistema
Los dispositivos Edge envían regularmente datos de sensores que incluyen múltiples mediciones (por ejemplo, temperatura, humedad, presión, etc.). Sin embargo, la base de datos remota donde se almacenan estos datos está configurada para aceptar solo un dato por fila. Además, el sistema debe asegurar que tanto los usuarios como los dispositivos estén autenticados correctamente para evitar el acceso no autorizado.

**Comment by diegote7** [comment]
se completa parte de la tarea
