### ISSUE TITLE
Uh3Tk3 - Configurar las rutas del middleware para interactuar con la API

### ISSUE THREAD

**Issue by FerCbr** [ISPC-TST-PI-I-2024/capa-de-procesamiento-grupo-plata#35]
### Uh3Tk3 - Configurar las rutas del middleware para interactuar con la API
**Descripción**: Configurar las rutas POST y GET en el middleware para interactuar correctamente con la API RESTful.
#### Pasos:
1. Crear rutas POST y GET en el middleware.
2. Implementar validación de datos en cada ruta.
3. Asegurar que las rutas devuelvan respuestas correctas a los dispositivos Edge.

**Comment by diegote7** [comment]
se crean rutas post y get

**Comment by NicolasBa27** [comment]
[README.md](https://github.com/user-attachments/files/17270745/README.md)
