### ISSUE TITLE
Uh3Tk4 - Integrar el middleware con el ESP32 y la API

### ISSUE THREAD

**Issue by FerCbr** [ISPC-TST-PI-I-2024/capa-de-procesamiento-grupo-plata#36]
### Uh3Tk4 - Integrar el middleware con el ESP32 y la API
**Descripción**: Integrar el middleware con los dispositivos ESP32 y la API para asegurar la correcta comunicación entre ellos.
#### Pasos:
1. Probar la conexión entre el ESP32 y el middleware.
2. Verificar que el middleware se comunica correctamente con la API RESTful.
3. Validar que los datos se reciben y almacenan correctamente en la base de datos.

**Comment by pleroldan** [comment]
Se agrega documentacion
