### ISSUE TITLE
Uh1Tk7 - Conectar remotamente al servidor

### ISSUE THREAD

**Issue by FerCbr** [ISPC-TST-PI-I-2024/capa-de-procesamiento-grupo-plata#6]
### Uh1Tk7 - Conectar remotamente al servidor
**Descripción**: Establecer una conexión remota segura al servidor utilizando SSH y realizar pruebas básicas para verificar el funcionamiento de la API y la base de datos.
#### Pasos:
1. Establecer una conexión SSH al servidor, documentando los pasos.
2. Verificar el estado de la API en el servidor ejecutando comandos básicos.
3. Realizar un ping a la base de datos para confirmar su conectividad.
4. Documentar el proceso de conexión remota y cualquier ajuste necesario.

**Comment by PaolaaPantoja** [comment]
CONEXIÓN SSH AL SERVIDOR
Para conectarnos de manera remota al servidor tenemos que ingresar al CMD (Command Prompt) o PowerShell, al abrirse la ventana se coloca el siguiente comando, correspondiente a nuestro grupo: 
ssh [plata@gonaiot.com](mailto:plata@gonaiot.com)
Al pedirnos una contraseña debemos ingresar lo siguiente: 
password: plata
![Imagen1](https://github.com/user-attachments/assets/a481da05-f8b8-4349-9e9d-2e6ee71e2201)

VERIFICACIÓN DEL ESTADO DE LA API
Para poder verificar el estado de la API necesitamos ejecutar el siguiente comando: curl -H "X-API-KEY: plata" https://api.gonaiot.com/plata/configuraciones/
![Captura](https://github.com/user-attachments/assets/62db7d6e-cc17-4caf-a7a4-cbe44a300716)

REALICE UN PING A LA BASE DE DATOS PARA CONFIRMAR SU CONECTIVIDAD
Al ser una base de datos en red interna, se accede usando su dirección IP en lugar del nombre de dominio:
IPv4 address for eth0: 192.168.0.100
![Captura2](https://github.com/user-attachments/assets/6a2794b1-a977-472a-a8fb-287d4daedde6)
